package com.oracle.anc.fmwpoc.sf.model.views;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 18 09:40:27 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OpportunitiesViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OppId {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppId();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppId((Number)value);
            }
        }
        ,
        OppTitle {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppTitle();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppTitle((String)value);
            }
        }
        ,
        AccId {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccId();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccId((Number)value);
            }
        }
        ,
        CntId {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getCntId();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setCntId((Number)value);
            }
        }
        ,
        OppSource {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppSource();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppSource((String)value);
            }
        }
        ,
        OppEstimatedAmount {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppEstimatedAmount();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppEstimatedAmount((Number)value);
            }
        }
        ,
        OppDescription {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppDescription();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppDescription((String)value);
            }
        }
        ,
        OppStatus {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppStatus();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppStatus((String)value);
            }
        }
        ,
        OppProbability {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppProbability();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppProbability((Number)value);
            }
        }
        ,
        EmpId {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getEmpId();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setEmpId((Number)value);
            }
        }
        ,
        ExpectedCloseDate {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getExpectedCloseDate();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setExpectedCloseDate((Date)value);
            }
        }
        ,
        CloseDate {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getCloseDate();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setCloseDate((Date)value);
            }
        }
        ,
        OppKeyMap {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getOppKeyMap();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setOppKeyMap((BlobDomain)value);
            }
        }
        ,
        AccName {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccName();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccName((String)value);
            }
        }
        ,
        CntName {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getCntName();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setCntName((String)value);
            }
        }
        ,
        AccAddress1 {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccAddress1();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccAddress1((String)value);
            }
        }
        ,
        AccCity {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccCity();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccCity((String)value);
            }
        }
        ,
        AccCountry {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccCountry();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccCountry((String)value);
            }
        }
        ,
        AccZip {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccZip();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccZip((String)value);
            }
        }
        ,
        AccId1 {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getAccId1();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAccId1((Number)value);
            }
        }
        ,
        LovModule_AccountsLovView1_1 {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getLovModule_AccountsLovView1_1();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovModule_ContactsLovView1_1 {
            public Object get(OpportunitiesViewRowImpl obj) {
                return obj.getLovModule_ContactsLovView1_1();
            }

            public void put(OpportunitiesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OpportunitiesViewRowImpl object);

        public abstract void put(OpportunitiesViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OPPID = AttributesEnum.OppId.index();
    public static final int OPPTITLE = AttributesEnum.OppTitle.index();
    public static final int ACCID = AttributesEnum.AccId.index();
    public static final int CNTID = AttributesEnum.CntId.index();
    public static final int OPPSOURCE = AttributesEnum.OppSource.index();
    public static final int OPPESTIMATEDAMOUNT = AttributesEnum.OppEstimatedAmount.index();
    public static final int OPPDESCRIPTION = AttributesEnum.OppDescription.index();
    public static final int OPPSTATUS = AttributesEnum.OppStatus.index();
    public static final int OPPPROBABILITY = AttributesEnum.OppProbability.index();
    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int EXPECTEDCLOSEDATE = AttributesEnum.ExpectedCloseDate.index();
    public static final int CLOSEDATE = AttributesEnum.CloseDate.index();
    public static final int OPPKEYMAP = AttributesEnum.OppKeyMap.index();
    public static final int ACCNAME = AttributesEnum.AccName.index();
    public static final int CNTNAME = AttributesEnum.CntName.index();
    public static final int ACCADDRESS1 = AttributesEnum.AccAddress1.index();
    public static final int ACCCITY = AttributesEnum.AccCity.index();
    public static final int ACCCOUNTRY = AttributesEnum.AccCountry.index();
    public static final int ACCZIP = AttributesEnum.AccZip.index();
    public static final int ACCID1 = AttributesEnum.AccId1.index();
    public static final int LOVMODULE_ACCOUNTSLOVVIEW1_1 = AttributesEnum.LovModule_AccountsLovView1_1.index();
    public static final int LOVMODULE_CONTACTSLOVVIEW1_1 = AttributesEnum.LovModule_ContactsLovView1_1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OpportunitiesViewRowImpl() {
    }

    /**
     * Gets Opportunities entity object.
     * @return the Opportunities
     */
    public EntityImpl getOpportunities() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets Accounts entity object.
     * @return the Accounts
     */
    public EntityImpl getAccounts() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for OPP_ID using the alias name OppId.
     * @return the OPP_ID
     */
    public Number getOppId() {
        return (Number) getAttributeInternal(OPPID);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_ID using the alias name OppId.
     * @param value value to set the OPP_ID
     */
    public void setOppId(Number value) {
        setAttributeInternal(OPPID, value);
    }

    /**
     * Gets the attribute value for OPP_TITLE using the alias name OppTitle.
     * @return the OPP_TITLE
     */
    public String getOppTitle() {
        return (String) getAttributeInternal(OPPTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_TITLE using the alias name OppTitle.
     * @param value value to set the OPP_TITLE
     */
    public void setOppTitle(String value) {
        setAttributeInternal(OPPTITLE, value);
    }

    /**
     * Gets the attribute value for ACC_ID using the alias name AccId.
     * @return the ACC_ID
     */
    public Number getAccId() {
        return (Number) getAttributeInternal(ACCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_ID using the alias name AccId.
     * @param value value to set the ACC_ID
     */
    public void setAccId(Number value) {
        setAttributeInternal(ACCID, value);
    }

    /**
     * Gets the attribute value for CNT_ID using the alias name CntId.
     * @return the CNT_ID
     */
    public Number getCntId() {
        return (Number) getAttributeInternal(CNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNT_ID using the alias name CntId.
     * @param value value to set the CNT_ID
     */
    public void setCntId(Number value) {
        setAttributeInternal(CNTID, value);
    }

    /**
     * Gets the attribute value for OPP_SOURCE using the alias name OppSource.
     * @return the OPP_SOURCE
     */
    public String getOppSource() {
        return (String) getAttributeInternal(OPPSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_SOURCE using the alias name OppSource.
     * @param value value to set the OPP_SOURCE
     */
    public void setOppSource(String value) {
        setAttributeInternal(OPPSOURCE, value);
    }

    /**
     * Gets the attribute value for OPP_ESTIMATED_AMOUNT using the alias name OppEstimatedAmount.
     * @return the OPP_ESTIMATED_AMOUNT
     */
    public Number getOppEstimatedAmount() {
        return (Number) getAttributeInternal(OPPESTIMATEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_ESTIMATED_AMOUNT using the alias name OppEstimatedAmount.
     * @param value value to set the OPP_ESTIMATED_AMOUNT
     */
    public void setOppEstimatedAmount(Number value) {
        setAttributeInternal(OPPESTIMATEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for OPP_DESCRIPTION using the alias name OppDescription.
     * @return the OPP_DESCRIPTION
     */
    public String getOppDescription() {
        return (String) getAttributeInternal(OPPDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_DESCRIPTION using the alias name OppDescription.
     * @param value value to set the OPP_DESCRIPTION
     */
    public void setOppDescription(String value) {
        setAttributeInternal(OPPDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OPP_STATUS using the alias name OppStatus.
     * @return the OPP_STATUS
     */
    public String getOppStatus() {
        return (String) getAttributeInternal(OPPSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_STATUS using the alias name OppStatus.
     * @param value value to set the OPP_STATUS
     */
    public void setOppStatus(String value) {
        setAttributeInternal(OPPSTATUS, value);
    }

    /**
     * Gets the attribute value for OPP_PROBABILITY using the alias name OppProbability.
     * @return the OPP_PROBABILITY
     */
    public Number getOppProbability() {
        return (Number) getAttributeInternal(OPPPROBABILITY);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_PROBABILITY using the alias name OppProbability.
     * @param value value to set the OPP_PROBABILITY
     */
    public void setOppProbability(Number value) {
        setAttributeInternal(OPPPROBABILITY, value);
    }

    /**
     * Gets the attribute value for EMP_ID using the alias name EmpId.
     * @return the EMP_ID
     */
    public Number getEmpId() {
        return (Number) getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ID using the alias name EmpId.
     * @param value value to set the EMP_ID
     */
    public void setEmpId(Number value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for EXPECTED_CLOSE_DATE using the alias name ExpectedCloseDate.
     * @return the EXPECTED_CLOSE_DATE
     */
    public Date getExpectedCloseDate() {
        return (Date) getAttributeInternal(EXPECTEDCLOSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPECTED_CLOSE_DATE using the alias name ExpectedCloseDate.
     * @param value value to set the EXPECTED_CLOSE_DATE
     */
    public void setExpectedCloseDate(Date value) {
        setAttributeInternal(EXPECTEDCLOSEDATE, value);
    }

    /**
     * Gets the attribute value for CLOSE_DATE using the alias name CloseDate.
     * @return the CLOSE_DATE
     */
    public Date getCloseDate() {
        return (Date) getAttributeInternal(CLOSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_DATE using the alias name CloseDate.
     * @param value value to set the CLOSE_DATE
     */
    public void setCloseDate(Date value) {
        setAttributeInternal(CLOSEDATE, value);
    }

    /**
     * Gets the attribute value for OPP_KEY_MAP using the alias name OppKeyMap.
     * @return the OPP_KEY_MAP
     */
    public BlobDomain getOppKeyMap() {
        return (BlobDomain) getAttributeInternal(OPPKEYMAP);
    }

    /**
     * Sets <code>value</code> as attribute value for OPP_KEY_MAP using the alias name OppKeyMap.
     * @param value value to set the OPP_KEY_MAP
     */
    public void setOppKeyMap(BlobDomain value) {
        setAttributeInternal(OPPKEYMAP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AccName.
     * @return the AccName
     */
    public String getAccName() {
        return (String) getAttributeInternal(ACCNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AccName.
     * @param value value to set the  AccName
     */
    public void setAccName(String value) {
        setAttributeInternal(ACCNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntName.
     * @return the CntName
     */
    public String getCntName() {
        return (String) getAttributeInternal(CNTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntName.
     * @param value value to set the  CntName
     */
    public void setCntName(String value) {
        setAttributeInternal(CNTNAME, value);
    }

    /**
     * Gets the attribute value for ACC_ADDRESS1 using the alias name AccAddress1.
     * @return the ACC_ADDRESS1
     */
    public String getAccAddress1() {
        return (String) getAttributeInternal(ACCADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_ADDRESS1 using the alias name AccAddress1.
     * @param value value to set the ACC_ADDRESS1
     */
    public void setAccAddress1(String value) {
        setAttributeInternal(ACCADDRESS1, value);
    }

    /**
     * Gets the attribute value for ACC_CITY using the alias name AccCity.
     * @return the ACC_CITY
     */
    public String getAccCity() {
        return (String) getAttributeInternal(ACCCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_CITY using the alias name AccCity.
     * @param value value to set the ACC_CITY
     */
    public void setAccCity(String value) {
        setAttributeInternal(ACCCITY, value);
    }

    /**
     * Gets the attribute value for ACC_COUNTRY using the alias name AccCountry.
     * @return the ACC_COUNTRY
     */
    public String getAccCountry() {
        return (String) getAttributeInternal(ACCCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_COUNTRY using the alias name AccCountry.
     * @param value value to set the ACC_COUNTRY
     */
    public void setAccCountry(String value) {
        setAttributeInternal(ACCCOUNTRY, value);
    }

    /**
     * Gets the attribute value for ACC_ZIP using the alias name AccZip.
     * @return the ACC_ZIP
     */
    public String getAccZip() {
        return (String) getAttributeInternal(ACCZIP);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_ZIP using the alias name AccZip.
     * @param value value to set the ACC_ZIP
     */
    public void setAccZip(String value) {
        setAttributeInternal(ACCZIP, value);
    }

    /**
     * Gets the attribute value for ACC_ID using the alias name AccId1.
     * @return the ACC_ID
     */
    public Number getAccId1() {
        return (Number) getAttributeInternal(ACCID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_ID using the alias name AccId1.
     * @param value value to set the ACC_ID
     */
    public void setAccId1(Number value) {
        setAttributeInternal(ACCID1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovModule_AccountsLovView1_1.
     */
    public RowSet getLovModule_AccountsLovView1_1() {
        return (RowSet)getAttributeInternal(LOVMODULE_ACCOUNTSLOVVIEW1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovModule_ContactsLovView1_1.
     */
    public RowSet getLovModule_ContactsLovView1_1() {
        return (RowSet)getAttributeInternal(LOVMODULE_CONTACTSLOVVIEW1_1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
