package com.oracle.anc.fmwpoc.sf.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 18 09:42:37 EET 2015
// ---------------------------------------------------------------------
public interface OpportunitiesView extends ViewObject {
    void refreshAccountsLOV();

    void refreshContactsLOV();
}
