-- USER SQL
CREATE USER sf IDENTIFIED BY sf ;

-- ROLES
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO sf ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO sf ;
GRANT "DELETE_CATALOG_ROLE" TO sf ;
GRANT "OEM_MONITOR" TO sf ;
GRANT "XDB_WEBSERVICES" TO sf ;
GRANT "HS_ADMIN_SELECT_ROLE" TO sf ;
GRANT "EXECUTE_CATALOG_ROLE" TO sf ;
GRANT "SCHEDULER_ADMIN" TO sf ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO sf ;
GRANT "RESOURCE" TO sf ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO sf ;
GRANT "AQ_USER_ROLE" TO sf ;
GRANT "APEX_ADMINISTRATOR_ROLE" TO sf ;
GRANT "SELECT_CATALOG_ROLE" TO sf ;
GRANT "CTXAPP" TO sf ;
GRANT "RECOVERY_CATALOG_OWNER" TO sf ;
GRANT "GATHER_SYSTEM_STATISTICS" TO sf ;
GRANT "DBA" TO sf ;
GRANT "CONNECT" TO sf ;
GRANT "AUTHENTICATEDUSER" TO sf ;
GRANT "XDB_SET_INVOKER" TO sf ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO sf ;
GRANT "PLUSTRACE" TO sf ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO sf ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO sf ;
GRANT "XDBADMIN" TO sf ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO sf ;
GRANT "EXP_FULL_DATABASE" TO sf ;
GRANT "IMP_FULL_DATABASE" TO sf ;
GRANT "HS_ADMIN_ROLE" TO sf ;
GRANT "DBFS_ROLE" TO sf ;
GRANT "OEM_ADVISOR" TO sf ;

-- SYSTEM PRIVILEGES
GRANT ALTER TABLESPACE TO sf ;
GRANT DROP ANY TRIGGER TO sf ;
GRANT CREATE USER TO sf ;
GRANT CREATE ANY OUTLINE TO sf ;
GRANT FLASHBACK ANY TABLE TO sf ;
GRANT ALTER ANY SEQUENCE TO sf ;
GRANT ALTER ANY LIBRARY TO sf ;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO sf ;
GRANT CREATE MINING MODEL TO sf ;
GRANT UPDATE ANY TABLE TO sf ;
GRANT UPDATE ANY CUBE TO sf ;
GRANT CREATE TRIGGER TO sf ;
GRANT DROP ANY EVALUATION CONTEXT TO sf ;
GRANT DROP PROFILE TO sf ;
GRANT CREATE TABLESPACE TO sf ;
GRANT DEBUG CONNECT SESSION TO sf ;
GRANT DROP ANY DIRECTORY TO sf ;
GRANT CREATE ASSEMBLY TO sf ;
GRANT SELECT ANY CUBE TO sf ;
GRANT CREATE SEQUENCE TO sf ;
GRANT ON COMMIT REFRESH TO sf ;
GRANT SELECT ANY SEQUENCE TO sf ;
GRANT CREATE ANY SQL PROFILE TO sf ;
GRANT DROP ANY SQL PROFILE TO sf ;
GRANT ADMINISTER ANY SQL TUNING SET TO sf ;
GRANT ADVISOR TO sf ;
GRANT ALTER ANY MINING MODEL TO sf ;
GRANT EXECUTE ANY OPERATOR TO sf ;
GRANT ALTER PROFILE TO sf ;
GRANT EXECUTE ANY TYPE TO sf ;
GRANT CREATE ANY DIRECTORY TO sf ;
GRANT CREATE TABLE TO sf ;
GRANT CREATE ANY INDEX TO sf ;
GRANT ADMINISTER RESOURCE MANAGER TO sf ;
GRANT BECOME USER TO sf ;
GRANT MANAGE TABLESPACE TO sf ;
GRANT DROP ANY MINING MODEL TO sf ;
GRANT EXECUTE ASSEMBLY TO sf ;
GRANT SELECT ANY TABLE TO sf ;
GRANT DROP ROLLBACK SEGMENT TO sf ;
GRANT CREATE OPERATOR TO sf ;
GRANT ALTER ANY CUBE TO sf ;
GRANT ALTER PUBLIC DATABASE LINK TO sf ;
GRANT CREATE ANY PROCEDURE TO sf ;
GRANT CREATE ANY CUBE TO sf ;
GRANT DROP ANY INDEXTYPE TO sf ;
GRANT SELECT ANY MINING MODEL TO sf ;
GRANT EXECUTE ANY CLASS TO sf ;
GRANT CREATE ANY MATERIALIZED VIEW TO sf ;
GRANT SELECT ANY TRANSACTION TO sf ;
GRANT ANALYZE ANY DICTIONARY TO sf ;
GRANT CREATE EXTERNAL JOB TO sf ;
GRANT INSERT ANY TABLE TO sf ;
GRANT CREATE LIBRARY TO sf ;
GRANT GRANT ANY OBJECT PRIVILEGE TO sf ;
GRANT CREATE JOB TO sf ;
GRANT CREATE ANY OPERATOR TO sf ;
GRANT ALTER ANY RULE TO sf ;
GRANT CREATE ANY LIBRARY TO sf ;
GRANT CREATE ANY SEQUENCE TO sf ;
GRANT DROP PUBLIC SYNONYM TO sf ;
GRANT CREATE CLUSTER TO sf ;
GRANT FORCE ANY TRANSACTION TO sf ;
GRANT UPDATE ANY CUBE DIMENSION TO sf ;
GRANT CREATE EVALUATION CONTEXT TO sf ;
GRANT CREATE ANY CUBE BUILD PROCESS TO sf ;
GRANT DROP ANY OPERATOR TO sf ;
GRANT DROP USER TO sf ;
GRANT EXECUTE ANY INDEXTYPE TO sf ;
GRANT ALTER ANY EDITION TO sf ;
GRANT LOCK ANY TABLE TO sf ;
GRANT DROP ANY TYPE TO sf ;
GRANT CHANGE NOTIFICATION TO sf ;
GRANT CREATE ANY DIMENSION TO sf ;
GRANT DROP ANY DIMENSION TO sf ;
GRANT READ ANY FILE GROUP TO sf ;
GRANT CREATE ANY RULE TO sf ;
GRANT ALTER ANY ASSEMBLY TO sf ;
GRANT EXEMPT IDENTITY POLICY TO sf ;
GRANT ALTER ROLLBACK SEGMENT TO sf ;
GRANT CREATE RULE TO sf ;
GRANT CREATE ANY VIEW TO sf ;
GRANT SYSOPER TO sf ;
GRANT CREATE PROCEDURE TO sf ;
GRANT INSERT ANY MEASURE FOLDER TO sf ;
GRANT SYSDBA TO sf ;
GRANT ANALYZE ANY TO sf ;
GRANT ALTER ANY TYPE TO sf ;
GRANT DROP ANY EDITION TO sf ;
GRANT CREATE ANY TRIGGER TO sf ;
GRANT MANAGE ANY FILE GROUP TO sf ;
GRANT DROP ANY RULE TO sf ;
GRANT CREATE DIMENSION TO sf ;
GRANT CREATE ROLLBACK SEGMENT TO sf ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO sf ;
GRANT ALTER ANY RULE SET TO sf ;
GRANT DROP ANY SEQUENCE TO sf ;
GRANT DROP ANY TABLE TO sf ;
GRANT CREATE CUBE DIMENSION TO sf ;
GRANT EXECUTE ANY RULE TO sf ;
GRANT DROP ANY LIBRARY TO sf ;
GRANT EXECUTE ANY PROCEDURE TO sf ;
GRANT DROP ANY VIEW TO sf ;
GRANT DROP ANY CONTEXT TO sf ;
GRANT FORCE TRANSACTION TO sf ;
GRANT CREATE ANY JOB TO sf ;
GRANT DROP ANY ROLE TO sf ;
GRANT DELETE ANY CUBE DIMENSION TO sf ;
GRANT DROP ANY CLUSTER TO sf ;
GRANT UPDATE ANY CUBE BUILD PROCESS TO sf ;
GRANT CREATE ANY INDEXTYPE TO sf ;
GRANT ADMINISTER SQL TUNING SET TO sf ;
GRANT EXECUTE ANY PROGRAM TO sf ;
GRANT DROP ANY ASSEMBLY TO sf ;
GRANT ALTER DATABASE LINK TO sf ;
GRANT GRANT ANY PRIVILEGE TO sf ;
GRANT ALTER ANY PROCEDURE TO sf ;
GRANT MERGE ANY VIEW TO sf ;
GRANT CREATE ANY EVALUATION CONTEXT TO sf ;
GRANT ALTER ANY OPERATOR TO sf ;
GRANT ALTER ANY CUBE DIMENSION TO sf ;
GRANT COMMENT ANY MINING MODEL TO sf ;
GRANT ALTER ANY ROLE TO sf ;
GRANT EXECUTE ANY ASSEMBLY TO sf ;
GRANT CREATE CUBE BUILD PROCESS TO sf ;
GRANT EXECUTE ANY RULE SET TO sf ;
GRANT ALTER ANY TRIGGER TO sf ;
GRANT UNDER ANY TABLE TO sf ;
GRANT BACKUP ANY TABLE TO sf ;
GRANT CREATE SYNONYM TO sf ;
GRANT DROP ANY CUBE BUILD PROCESS TO sf ;
GRANT DROP ANY CUBE TO sf ;
GRANT ALTER DATABASE TO sf ;
GRANT ALTER ANY TABLE TO sf ;
GRANT CREATE VIEW TO sf ;
GRANT EXECUTE ANY LIBRARY TO sf ;
GRANT CREATE RULE SET TO sf ;
GRANT EXEMPT ACCESS POLICY TO sf ;
GRANT CREATE ANY CLUSTER TO sf ;
GRANT DROP ANY INDEX TO sf ;
GRANT CREATE TYPE TO sf ;
GRANT EXECUTE ANY EVALUATION CONTEXT TO sf ;
GRANT ALTER RESOURCE COST TO sf ;
GRANT ALTER ANY CLUSTER TO sf ;
GRANT CREATE PUBLIC SYNONYM TO sf ;
GRANT ALTER ANY INDEX TO sf ;
GRANT CREATE ANY MINING MODEL TO sf ;
GRANT GLOBAL QUERY REWRITE TO sf ;
GRANT CREATE ANY RULE SET TO sf ;
GRANT CREATE MEASURE FOLDER TO sf ;
GRANT DROP ANY CUBE DIMENSION TO sf ;
GRANT CREATE ROLE TO sf ;
GRANT RESTRICTED SESSION TO sf ;
GRANT DROP ANY PROCEDURE TO sf ;
GRANT ALTER USER TO sf ;
GRANT CREATE ANY CONTEXT TO sf ;
GRANT CREATE ANY SYNONYM TO sf ;
GRANT CREATE ANY CUBE DIMENSION TO sf ;
GRANT ALTER ANY OUTLINE TO sf ;
GRANT ENQUEUE ANY QUEUE TO sf ;
GRANT CREATE ANY TABLE TO sf ;
GRANT SELECT ANY CUBE DIMENSION TO sf ;
GRANT ALTER ANY EVALUATION CONTEXT TO sf ;
GRANT CREATE SESSION TO sf ;
GRANT DEQUEUE ANY QUEUE TO sf ;
GRANT QUERY REWRITE TO sf ;
GRANT EXPORT FULL DATABASE TO sf ;
GRANT CREATE PUBLIC DATABASE LINK TO sf ;
GRANT RESUMABLE TO sf ;
GRANT UNLIMITED TABLESPACE TO sf ;
GRANT UNDER ANY VIEW TO sf ;
GRANT DROP ANY OUTLINE TO sf ;
GRANT CREATE ANY EDITION TO sf ;
GRANT CREATE ANY ASSEMBLY TO sf ;
GRANT ALTER ANY INDEXTYPE TO sf ;
GRANT DROP ANY MATERIALIZED VIEW TO sf ;
GRANT CREATE INDEXTYPE TO sf ;
GRANT ALTER ANY SQL PROFILE TO sf ;
GRANT ALTER SYSTEM TO sf ;
GRANT DROP ANY SYNONYM TO sf ;
GRANT GRANT ANY ROLE TO sf ;
GRANT CREATE MATERIALIZED VIEW TO sf ;
GRANT DROP ANY RULE SET TO sf ;
GRANT MANAGE SCHEDULER TO sf ;
GRANT DROP TABLESPACE TO sf ;
GRANT SELECT ANY DICTIONARY TO sf ;
GRANT IMPORT FULL DATABASE TO sf ;
GRANT DELETE ANY MEASURE FOLDER TO sf ;
GRANT DELETE ANY TABLE TO sf ;
GRANT AUDIT SYSTEM TO sf ;
GRANT ALTER ANY MATERIALIZED VIEW TO sf ;
GRANT DEBUG ANY PROCEDURE TO sf ;
GRANT CREATE PROFILE TO sf ;
GRANT CREATE ANY MEASURE FOLDER TO sf ;
GRANT UNDER ANY TYPE TO sf ;
GRANT COMMENT ANY TABLE TO sf ;
GRANT ALTER ANY DIMENSION TO sf ;
GRANT CREATE ANY TYPE TO sf ;
GRANT DROP ANY MEASURE FOLDER TO sf ;
GRANT DROP PUBLIC DATABASE LINK TO sf ;
GRANT CREATE CUBE TO sf ;
GRANT CREATE DATABASE LINK TO sf ;
GRANT INSERT ANY CUBE DIMENSION TO sf ;
GRANT ALTER SESSION TO sf ;
GRANT MANAGE ANY QUEUE TO sf ;
GRANT ADMINISTER DATABASE TRIGGER TO sf ;
GRANT AUDIT ANY TO sf ;
GRANT MANAGE FILE GROUP TO sf ;

-- QUOTAS
ALTER USER sf QUOTA UNLIMITED ON USERS;
ALTER USER sf QUOTA UNLIMITED ON TEMP;

CREATE TABLE SF.ACCOUNTS 
(
  ACC_ID NUMBER NOT NULL 
, ACC_NAME VARCHAR2(255 CHAR) NOT NULL 
, ACC_ADDRESS1 VARCHAR2(255 CHAR) 
, ACC_ADDRESS2 VARCHAR2(255 CHAR) 
, ACC_ZIP VARCHAR2(50 CHAR) 
, ACC_CITY VARCHAR2(255 CHAR) 
, ACC_COUNTRY VARCHAR2(255 CHAR) 
, ACC_VATID VARCHAR2(50 CHAR) 
, ACC_TWITTER VARCHAR2(50 BYTE) 
, ACC_FACEBOOK VARCHAR2(50 BYTE) 
, ACC_WWW VARCHAR2(255 BYTE) 
, ACC_FORUM_ID VARCHAR2(255 BYTE) 
, ACC_STOCK_SYMBOL VARCHAR2(20 BYTE) 
, CONSTRAINT ACCOUNTS_PK PRIMARY KEY 
  (
    ACC_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.ACCOUNTS_PK ON SF.ACCOUNTS (ACC_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SF.CNT_ACTIONS 
(
  CNT_ACTION_ID NUMBER NOT NULL 
, CNT_ID NUMBER 
, EMP_ID NUMBER 
, ACT_DATE DATE 
, ACT_TYPE VARCHAR2(50 BYTE) 
, ACT_DESCRIPTION VARCHAR2(2048 BYTE) 
, ACT_START_DATE DATE 
, ACT_END_DATE DATE 
, CONSTRAINT CNT_ACTIONS_PK PRIMARY KEY 
  (
    CNT_ACTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.CNT_ACTIONS_PK ON SF.CNT_ACTIONS (CNT_ACTION_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SF.CONTACTS 
(
  CNT_ID NUMBER NOT NULL 
, ACC_ID NUMBER NOT NULL 
, CNT_TITLE VARCHAR2(20 CHAR) 
, CNT_NAME VARCHAR2(255 CHAR) NOT NULL 
, CNT_JOB_TITLE VARCHAR2(255 CHAR) 
, CNT_PHONE VARCHAR2(255 CHAR) 
, CNT_MOBILE VARCHAR2(255 CHAR) 
, CNT_EMAIL VARCHAR2(255 CHAR) 
, CNT_FAX VARCHAR2(255 CHAR) 
, CNT_NOTES VARCHAR2(2048 CHAR) 
, CNT_MANAGER_ID NUMBER 
, CNT_PHOTO BLOB 
, CONSTRAINT CONTACTS_PK PRIMARY KEY 
  (
    CNT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.CONTACTS_PK ON SF.CONTACTS (CNT_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
LOB (CNT_PHOTO) STORE AS SYS_LOB0000020371C00012$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE SF.DISCOUNTS 
(
  DIS_ID NUMBER NOT NULL 
, OPP_ID NUMBER NOT NULL 
, DIS_STATE VARCHAR2(30 BYTE) NOT NULL 
, DIS_APPROVER VARCHAR2(30 BYTE) 
, DIS_NOTE VARCHAR2(2000 BYTE) 
, DIS_APPROVER_NOTE VARCHAR2(2000 BYTE) 
, DIS_PROBABILITY_WITH NUMBER(3, 0) NOT NULL 
, DIS_PROBABILITY_WITHOUT NUMBER(3, 0) NOT NULL 
, DIS_REQUESTED_ON DATE 
, DIS_DECIDED_ON DATE 
, DIS_PERCENT NUMBER(3, 0) 
, DIS_TOP_APPROVER VARCHAR2(30 BYTE) 
, CONSTRAINT DISCOUNTS_PK PRIMARY KEY 
  (
    DIS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.DISCOUNTS_PK ON SF.DISCOUNTS (DIS_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SF.EMPLOYEES 
(
  EMP_ID NUMBER NOT NULL 
, EMP_NAME VARCHAR2(255 CHAR) NOT NULL 
, EMP_JOB_TITLE VARCHAR2(255 CHAR) 
, MANAGER_ID NUMBER 
, EMP_EMAIL VARCHAR2(255 CHAR) 
, EMP_PHONE VARCHAR2(255 CHAR) 
, EMP_YEARLY_TARGET_AMOUNT NUMBER(10, 0) DEFAULT 0 NOT NULL 
, EMP_PHOTO BLOB 
, USERNAME VARCHAR2(255 CHAR) 
, PASSWORD VARCHAR2(255 CHAR) 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    EMP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.EMPLOYEES_PK ON SF.EMPLOYEES (EMP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
LOB (EMP_PHOTO) STORE AS SYS_LOB0000016666C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE SF.OPPORTUNITIES 
(
  OPP_ID NUMBER NOT NULL 
, OPP_TITLE VARCHAR2(255 CHAR) NOT NULL 
, ACC_ID NUMBER NOT NULL 
, CNT_ID NUMBER 
, OPP_SOURCE VARCHAR2(255 CHAR) 
, OPP_ESTIMATED_AMOUNT NUMBER 
, OPP_DESCRIPTION VARCHAR2(2048 CHAR) 
, OPP_STATUS VARCHAR2(50 CHAR) DEFAULT 'LEAD' NOT NULL 
, OPP_PROBABILITY NUMBER(3, 0) DEFAULT 0 NOT NULL 
, EMP_ID NUMBER 
, EXPECTED_CLOSE_DATE DATE 
, CLOSE_DATE DATE 
, OPP_KEY_MAP BLOB 
, CONSTRAINT OPPORTUNITIES_PK PRIMARY KEY 
  (
    OPP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SF.OPPORTUNITIES_PK ON SF.OPPORTUNITIES (OPP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
LOB (OPP_KEY_MAP) STORE AS SYS_LOB0000016249C00013$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE VIEW SF.VW_STAGES AS select '1-25%' as stage from dual
union all
select '25-50%' from dual
union all
select '50-75%' from dual
union all
select '75-99%' from dual;

CREATE VIEW SF.VW_QUARTERS AS select to_char(sysdate,'YYYY\')||'1' q from dual
union all
select to_char(sysdate,'YYYY\')||'2' from dual
union all
select to_char(sysdate,'YYYY\')||'3' from dual
union all
select to_char(sysdate,'YYYY\')||'4' from dual;

CREATE VIEW SF.VW_OPP AS select
  case 
    when opp_status ='WON' then '99-WON'
    when opp_probability < 25 then '1-25%'
    when opp_probability < 50 then '25-50%'
    when opp_probability < 75 then '50-75%'
    else '75-99%'
  end as stage,
  opp_estimated_amount,
  opp_estimated_amount*(opp_probability/100) as probable_amount,
  emp_id,
  expected_close_date,
  to_char(expected_close_date,'YYYY\Q') expected_close_quarter,
  opp_status,
  close_date,
 to_char(close_date,'YYYY\Q') close_quarter,
 acc_id
from opportunities opp
WHERE opp.opp_status in ('LEAD','OPP','WON');

CREATE VIEW SF.VW_EMP_TARGET AS with opp as 
  (select emp_id,sum(opp.opp_estimated_amount) closed_amount from opportunities opp
   where trunc(opp.close_date,'YEAR')=trunc(sysdate,'YEAR') group by emp_id)
select emp.emp_id,opp.closed_amount,emp.emp_yearly_target_amount target_amount from employees emp 
left join opp on emp.emp_id=opp.emp_id;

CREATE VIEW SF.USERS AS select password u_password, username u_name from employees emp;

CREATE VIEW SF.GROUPS AS select 'employees' g_name from dual
union all
select 'managers' g_name from dual;

CREATE VIEW SF.GROUPMEMBERS AS select username g_member, 'employees' g_name
from employees
union all
select username g_member, 'managers' g_name
from employees emp where exists (select 1 from employees em1 where em1.manager_id=emp.emp_id);

CREATE VIEW SF.VW_OPP_EMP AS with opp as (
SELECT
  EMP_ID,
  STAGE,
  SUM(OPP_ESTIMATED_AMOUNT) OPP_ESTIMATED_AMOUNT,
  SUM(PROBABLE_AMOUNT) PROBABLE_AMOUNT
FROM 
  VW_OPP GROUP BY EMP_ID, STAGE
ORDER BY STAGE)
select 
emp.emp_id,
emp.stage,
opp.OPP_ESTIMATED_AMOUNT,
opp.PROBABLE_AMOUNT,
/*case 
  when stage='1-25%' then emp.emp_yearly_target_amount/0.25
  when stage='25-50%' then emp.emp_yearly_target_amount/0.5
  when stage='50-75%' then emp.emp_yearly_target_amount/0.75
  when stage='75-99%' then emp.emp_yearly_target_amount/0.95
  else emp_yearly_target_amount
end / 4 as stage_target -- 4 is a constant - length of sales cycle
*/
emp_yearly_target_amount stage_target
from (select * from vw_stages
cross join employees) emp 
left join opp on opp.stage=emp.stage and emp.emp_id=opp.emp_id;

CREATE VIEW SF.VW_OPP_COUNTRIES AS with opp as (select
  acc_country,
  opportunities.stage,
  sum(opportunities.opp_estimated_amount) opp_estimated_amount
FROM 
    VW_OPP OPPORTUNITIES JOIN ACCOUNTS ACCOUNTS1 USING (ACC_ID) 
    WHERE
OPPORTUNITIES.OPP_STATUS IN ('LEAD','OPPORTUNITY')
group by acc_country, opportunities.stage )

select acc_country,
  max(decode( stage, '1-25%', opp_estimated_amount, NULL )) "1-25%",
  max(decode( stage, '25-50%', opp_estimated_amount, NULL )) "25-50%",
 max(decode( stage, '50-75%', opp_estimated_amount, NULL )) "50-75%",
 max(decode( stage, '75-99%', opp_estimated_amount, NULL )) "75-99%"
from opp t
group by acc_country;

CREATE VIEW SF.VW_EMP_EXPECTED_CLOSE_Q AS with opp as (
select 
  sum(probable_amount) probable_amount,
  emp_id,
  expected_close_quarter
from 
  vw_opp 
where opp_status in ('LEAD','OPP') group by emp_id, expected_close_quarter
)
select
opp."PROBABLE_AMOUNT",opp."EMP_ID",opp."EXPECTED_CLOSE_QUARTER",
emp.emp_yearly_target_amount/4 emp_quarterly_target_amount
from opp
inner join employees emp on emp.emp_id=opp.emp_id
order by opp.expected_close_quarter;

CREATE VIEW SF.VW_EMP_CLOSE_Q AS with opp as (
select 
  sum(opp_estimated_amount) closed_amount,
  emp_id,
  close_quarter
from 
  vw_opp 
where opp_status in ('WON') group by emp_id, close_quarter
)
select
opp."CLOSED_AMOUNT",opp."EMP_ID",opp."CLOSE_QUARTER",
emp.emp_yearly_target_amount/4 emp_quarterly_target_amount
from opp
inner join employees emp on emp.emp_id=opp.emp_id
order by opp.close_quarter;

CREATE VIEW SF.VW_EMP_QUARTER_REPORT AS select 
  emp.emp_id,
  emp.q quarter,
  eeq.probable_amount,
  nvl(ecq.closed_amount,0) closed_amount,
  nvl(eeq.emp_quarterly_target_amount,ecq.emp_quarterly_target_amount) emp_quarterly_target_amount
from 
(SELECT emp.emp_id,qts.* FROM vw_quarters qts
cross join employees emp) emp
left join vw_emp_expected_close_q eeq on eeq.emp_id=emp.emp_id and eeq.expected_close_quarter=emp.q
left join vw_emp_close_q ecq on ecq.emp_id=emp.emp_id and ecq.close_quarter=emp.q;

ALTER TABLE SF.ACCOUNTS
ADD CONSTRAINT ACCOUNTS_UK1 UNIQUE 
(
  ACC_NAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX SF.ACCOUNTS_UK1 ON SF.ACCOUNTS (ACC_NAME ASC) 
    LOGGING 
    TABLESPACE "USERS" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE SF.CNT_ACTIONS
ADD CONSTRAINT CNT_ACTIONS_CONTACTS_FK1 FOREIGN KEY
(
  CNT_ID 
)
REFERENCES SF.CONTACTS
(
  CNT_ID 
)
ENABLE;

ALTER TABLE SF.CNT_ACTIONS
ADD CONSTRAINT CNT_ACTIONS_EMPLOYEES_FK1 FOREIGN KEY
(
  EMP_ID 
)
REFERENCES SF.EMPLOYEES
(
  EMP_ID 
)
ENABLE;

ALTER TABLE SF.CONTACTS
ADD CONSTRAINT CONTACTS_ACCOUNTS_FK1 FOREIGN KEY
(
  ACC_ID 
)
REFERENCES SF.ACCOUNTS
(
  ACC_ID 
)
ENABLE;

ALTER TABLE SF.CONTACTS
ADD CONSTRAINT CONTACTS_CONTACTS_FK1 FOREIGN KEY
(
  CNT_MANAGER_ID 
)
REFERENCES SF.CONTACTS
(
  CNT_ID 
)
ENABLE;

ALTER TABLE SF.DISCOUNTS
ADD CONSTRAINT DIS_OPP_FK FOREIGN KEY
(
  OPP_ID 
)
REFERENCES SF.OPPORTUNITIES
(
  OPP_ID 
)
ENABLE;

ALTER TABLE SF.EMPLOYEES
ADD CONSTRAINT EMP_MANAGER_FK1 FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES SF.EMPLOYEES
(
  EMP_ID 
)
ENABLE;

ALTER TABLE SF.OPPORTUNITIES
ADD CONSTRAINT OPP_ACC_FK1 FOREIGN KEY
(
  ACC_ID 
)
REFERENCES SF.ACCOUNTS
(
  ACC_ID 
)
ENABLE;

ALTER TABLE SF.OPPORTUNITIES
ADD CONSTRAINT OPP_CNT_FK1 FOREIGN KEY
(
  CNT_ID 
)
REFERENCES SF.CONTACTS
(
  CNT_ID 
)
ENABLE;

ALTER TABLE SF.OPPORTUNITIES
ADD CONSTRAINT OPP_EMP_FK1 FOREIGN KEY
(
  EMP_ID 
)
REFERENCES SF.EMPLOYEES
(
  EMP_ID 
)
ENABLE;

ALTER TABLE SF.OPPORTUNITIES
ADD CONSTRAINT OPP_DESCRIPTION_CHK CHECK 
(OPP_STATUS IN ('LEAD', 'OPPORTUNITY', 'WON', 'LOST'))
ENABLE;

ALTER TABLE SF.OPPORTUNITIES
ADD CONSTRAINT OPP_PROBABILITY_CHECK CHECK 
(OPP_PROBABILITY >= 0 AND OPP_PROBABILITY <= 100)
ENABLE;

CREATE SEQUENCE SF.SF_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TRIGGER SF.ACCOUNTS_TRG BEFORE INSERT ON SF.ACCOUNTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ACC_ID IS NULL THEN
      SELECT SF_SEQ.NEXTVAL INTO :NEW.ACC_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER SF.CNT_ACTIONS_TRG BEFORE INSERT ON "SF".CNT_ACTIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CNT_ACTION_ID IS NULL THEN
      SELECT SF_SEQ.NEXTVAL INTO :NEW.CNT_ACTION_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER SF.CONTACTS_TRG BEFORE INSERT ON SF.CONTACTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CNT_ID IS NULL THEN
      SELECT SF_SEQ.NEXTVAL INTO :NEW.CNT_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER SF."DISCOUNTS_TRG" BEFORE
  INSERT ON "SF".DISCOUNTS FOR EACH ROW BEGIN IF :NEW.DIS_ID IS NULL THEN
  SELECT SF_SEQ.NEXTVAL INTO :NEW.DIS_ID FROM DUAL;
END IF;
END;
/

CREATE TRIGGER SF.EMPLOYEES_TRG BEFORE INSERT ON SF.EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.EMP_ID IS NULL THEN
      SELECT SF_SEQ.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER SF.OPPORTUNITIES_TRG BEFORE INSERT ON SF.OPPORTUNITIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.OPP_ID IS NULL THEN
      SELECT SF_SEQ.NEXTVAL INTO :NEW.OPP_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

REM INSERTING into SF.ACCOUNTS
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (32,'P Global Adm','Delavska cesta 24',null,'4208','�en�ur','Slovenia',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (34,'First Securities LLC',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (203,'Ace Innovation',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (391,'Superior Outsourcing Ltd','Dunajska 152',null,'1000','Ljubljana','Slovenija',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (60,'Indicative Unified Corporation',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (1,'Acme Ltd.','Calea Floreasca Nr. 169 A',null,null,'Bucharest','Romania',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (55,'Indicative Digital Firm',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (78,'Advanced Integrity',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (36,'American Client Inc',null,null,null,null,null,null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (320,'Technical Interworks','Rewolucji 1905r. 65',null,'90-221','��d�','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (324,'Open Solutions','PIOTRKOWSKA 148/150',null,'90-063','��d�','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (325,'Enigma Integrity','Wadowicka 6e',null,'30-444','Krak�w','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (326,'Quantum Computation Studios','al. Jana Paw�a II 39a',null,'31-864','Krak�w','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (327,'Universal Automation','Powsta�c�w �l�skich 89a/212',null,'01-355','WArszawa','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (328,'Superior Canadian','Al. Jana Paw�a II 20/611',null,'00-133','Warszawa','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (329,'Experts Technologies','Prosta 51',null,'00-838','Warszawa','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (330,'Silicon Intelligent','Delavska cesta 24',null,'4208','�en�ur','Slovenia',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (331,'Network Total','Wyspia�skiego 27',null,'50-370','Wroc�aw','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (332,'Advanced Technologies','Sowi�skiego 3',null,'44-100','Gliwice','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (333,'Visual Worldwide','Kaszubska 6',null,'50-214','Wroc�aw','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (334,'C Solutions','Broniewskiego 7/17',null,'82-500','Kwidzyn','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (335,'Key Concepts','Sosnkowskiego 29',null,'02-495','Warszawa','Poland',null);
Insert into SF.ACCOUNTS (ACC_ID,ACC_NAME,ACC_ADDRESS1,ACC_ADDRESS2,ACC_ZIP,ACC_CITY,ACC_COUNTRY,ACC_VATID) values (474,'frufru',null,null,null,null,null,null);
REM INSERTING into SF.CONTACTS
Insert into SF.CONTACTS (CNT_ID,ACC_ID,CNT_TITLE,CNT_NAME,CNT_JOB_TITLE,CNT_PHONE,CNT_MOBILE,CNT_EMAIL,CNT_FAX,CNT_NOTES) values (53,1,'Mr','Contact Man',null,null,null,null,null,null);
Insert into SF.CONTACTS (CNT_ID,ACC_ID,CNT_TITLE,CNT_NAME,CNT_JOB_TITLE,CNT_PHONE,CNT_MOBILE,CNT_EMAIL,CNT_FAX,CNT_NOTES) values (392,391,'Mr.','John Doe','CEO',null,null,null,null,null);
Insert into SF.CONTACTS (CNT_ID,ACC_ID,CNT_TITLE,CNT_NAME,CNT_JOB_TITLE,CNT_PHONE,CNT_MOBILE,CNT_EMAIL,CNT_FAX,CNT_NOTES) values (56,55,null,'Dcme man',null,null,null,null,null,null);
Insert into SF.CONTACTS (CNT_ID,ACC_ID,CNT_TITLE,CNT_NAME,CNT_JOB_TITLE,CNT_PHONE,CNT_MOBILE,CNT_EMAIL,CNT_FAX,CNT_NOTES) values (214,1,'Mr','Jernej',null,null,null,null,null,null);
REM INSERTING into SF.EMPLOYEES
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (72,'Demetris Skourides','Sales Director EE_CIS',null,null,null,60000000,'demetris','password');
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (73,'Ruxandra Radulescu','Sales Manager DB _ Options EE_CIS',72,null,null,12000000,'ruxandra','password');
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (414,'Assia Toumbanova','Sales Manager Bulgaria',73,null,null,8000000,null,null);
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (415,'Matthieu Jamme','Sales Manager EE',72,null,null,18000000,null,null);
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (416,'Thanos Printzios','Sales Manager SE',72,null,null,20000000,null,null);
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (231,'Gregor Rayman','Sales Manager FMW EE_CIS',72,null,null,30000000,'gregor','password');
Insert into SF.EMPLOYEES (EMP_ID,EMP_NAME,EMP_JOB_TITLE,MANAGER_ID,EMP_EMAIL,EMP_PHONE,EMP_YEARLY_TARGET_AMOUNT,USERNAME,PASSWORD) values (229,'Jernej Ka�e','Chief Architect _ Evangelist',231,null,null,5000000,'jernej','password');

REM INSERTING into SF.OPPORTUNITIES
REM INSERTING into OPPORTUNITIES
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (74,'WebCenter',78,null,'asd',4765716.01092790744666974097261913799894,null,'LEAD',56,73,to_timestamp('24-JAN-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (75,'WebLogic',1,null,'wed',1062946.91661667912221101250660358728041,null,'LEAD',43,73,to_timestamp('14-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (76,'ADF',1,null,'dd',8513027,null,'WON',88,73,to_timestamp('31-MAY-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('18-JUN-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (241,'IDM + WebCenter',1,53,null,973318,null,'LEAD',83,229,to_timestamp('27-SEP-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (417,'fejk promet demetris',1,53,null,17211527,null,'WON',17,415,to_timestamp('31-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('20-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (418,'WebLogic + IDM',1,53,null,12447705,null,'LEAD',100,415,to_timestamp('20-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (419,'Golden Gate and DB EE',1,53,null,15175786,null,'LEAD',68,415,to_timestamp('05-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (420,'FMW + Applications',1,null,null,4235488,null,'LEAD',91,415,to_timestamp('11-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (421,'WebLogic Virtual Edition',1,53,null,16896645,null,'LEAD',34,415,to_timestamp('16-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (422,'DB Options + Coherence',1,53,null,6159977,null,'OPPORTUNITY',43,415,to_timestamp('21-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (423,'fejk promet demetris',1,53,null,14711527,null,'WON',17,416,to_timestamp('31-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('20-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (424,'WebLogic + IDM',1,53,null,4447705,null,'LEAD',100,416,to_timestamp('20-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (425,'Golden Gate and DB EE',1,53,null,15175786,null,'LEAD',68,416,to_timestamp('05-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (426,'FMW + Applications',1,null,null,4235488,null,'LEAD',91,416,to_timestamp('11-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (427,'WebLogic Virtual Edition',1,53,null,16896645,null,'LEAD',34,416,to_timestamp('16-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (428,'DB Options + Coherence',1,53,null,6159977,null,'OPPORTUNITY',43,416,to_timestamp('21-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (429,'fejk promet demetris',1,53,null,3711527,null,'WON',17,414,to_timestamp('31-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('20-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (430,'WebLogic + IDM',1,53,null,8447705,null,'LEAD',100,414,to_timestamp('20-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (431,'Golden Gate and DB EE',1,53,null,1175786,null,'LEAD',68,414,to_timestamp('05-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (432,'FMW + Applications',1,null,null,4235488,null,'LEAD',91,414,to_timestamp('11-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (433,'WebLogic Virtual Edition',1,53,null,16896645,null,'LEAD',34,414,to_timestamp('16-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (434,'DB Options + Coherence',1,53,null,6159977,null,'OPPORTUNITY',43,414,to_timestamp('21-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (10,'DB Options',1,null,'aa',346456.752105512083866019085935722676148,'aaa','LEAD',23,73,to_timestamp('04-FEB-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (223,'FMW',1,53,null,3132049.92760709750572777175710232455702,'New lead<p></p>','LEAD',60,73,to_timestamp('05-JUL-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (349,'fejk promet jernej',1,53,null,2800000,null,'WON',99,229,to_timestamp('07-APR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('19-JUN-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (350,'fejk promet gregor',1,53,null,18720150,null,'WON',55,231,to_timestamp('09-OCT-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('20-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (351,'fejk promet demetris',1,53,null,30711527,null,'WON',17,72,to_timestamp('31-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('20-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (6,'Golden Gate',1,null,'aa',2312176.38882018475945283170460428967505,'a','LEAD',88,73,to_timestamp('26-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (272,'WebLogic + IDM',1,53,null,8447705,null,'LEAD',100,72,to_timestamp('20-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (292,'Golden Gate and DB EE',1,53,null,15175786,null,'LEAD',68,72,to_timestamp('05-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (323,'ADF ISV',320,null,null,818312.842839255228686403189287419002121,null,'LEAD',96,229,to_timestamp('15-FEB-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (393,'fejk promet jernej 2',1,53,null,1100000,null,'WON',99,229,null,to_timestamp('21-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (394,'Coherence',1,53,null,3412000,null,'WON',100,73,to_timestamp('21-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'),to_timestamp('21-JUL-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'));
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (31,'Grid Control',32,null,null,3933263.33423997952164114422144529833888,null,'LEAD',84,73,to_timestamp('17-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (79,'FMW + Applications',1,null,'wed',4235488,'ss','LEAD',91,72,to_timestamp('11-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (80,'WebLogic Virtual Edition',1,53,'wed',16896645,'ss','LEAD',34,72,to_timestamp('16-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (215,'ADF + WebLogic cluster',1,53,null,11912383,'Demo 123<p></p>','LEAD',51,null,to_timestamp('16-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (221,'New lead yeah',1,53,null,2248589.99518331774143000612580153741319,null,'LEAD',3,73,to_timestamp('02-AUG-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (337,'Open Solutions ADF',324,null,'ADF Workshop',321732.679534568186770052584586357353462,null,'LEAD',72,229,to_timestamp('12-JUL-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (338,'Enigma Integrity ADF',325,null,'ADF Workshop',997770.161124886877637034567392454045105,null,'LEAD',34,229,to_timestamp('19-AUG-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (339,'Quantum ADF',326,null,'ADF Workshop',981388.853756476398083637675172227072673,null,'LEAD',4,229,to_timestamp('30-SEP-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (340,'Cube-cr ADF',327,null,'ADF Workshop',711095.504367585823620565033907652213163,null,'LEAD',23,229,to_timestamp('25-MAR-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (341,'Evcon ADF',328,null,'ADF Workshop',677132.613319322162151135672194660607793,null,'LEAD',58,229,to_timestamp('22-OCT-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (342,'Infovide-Matrix S.A. ADF',329,null,'ADF Workshop',877294.054466117770168550792686946326381,null,'LEAD',10,229,to_timestamp('23-FEB-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (343,'Interia.pl ADF',330,null,'ADF Workshop',201806.628414910211312594733426315486832,null,'LEAD',76,229,to_timestamp('09-OCT-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (344,'Politechnika Wroc�awska ADF',331,null,'ADF Workshop',467275.960696135126430212266444609302524,null,'LEAD',96,229,to_timestamp('30-SEP-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (345,'Prolan ADF',332,null,'ADF Workshop',889341.511103324956148815356005982120877,null,'LEAD',43,229,to_timestamp('19-JUN-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (346,'SHH Sp. z o.o. ADF',333,null,'ADF Workshop',837125.512914743126291183241816124717843,null,'LEAD',84,229,to_timestamp('11-OCT-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (347,'Sollers Consulting Sp. z o.o. ADF',334,null,'ADF Workshop',114858.109715166881002542739761902849626,null,'LEAD',93,229,to_timestamp('13-JUL-12 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (348,'Xentivo ADF',335,null,'ADF Workshop',803531.070950630369288396967268691100031,null,'LEAD',64,229,to_timestamp('21-JUL-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (242,'WebLogic + WebCenter',1,53,null,1508511,null,'LEAD',85,229,to_timestamp('25-AUG-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (246,'DB Options + Coherence',1,53,null,6159977,null,'OPPORTUNITY',43,72,to_timestamp('21-AUG-11 12.25.59.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (64,'test train',1,53,null,123,null,'LEAD',20,null,to_timestamp('12-OCT-11 12.00.00.000000000','DD-MON-RR HH.MI.SS.FF'),null);
Insert into SF.OPPORTUNITIES (OPP_ID,OPP_TITLE,ACC_ID,CNT_ID,OPP_SOURCE,OPP_ESTIMATED_AMOUNT,OPP_DESCRIPTION,OPP_STATUS,OPP_PROBABILITY,EMP_ID,EXPECTED_CLOSE_DATE,CLOSE_DATE) values (1016,'aaa1',1,null,null,null,null,'LEAD',0,null,null,null);
